export const ACTIONS = {
  CREATE_USER: "CREATE_USER",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_ERROR: "CREATE_USER_ERROR",
  SIGNIN_USER: "SIGNIN_USER",
  SIGNIN_USER_SUCCESS: "SIGNIN_USER_SUCCESS",
  SIGNIN_USER_ERROR: "SIGNIN_USER_ERROR",
  SIGNOUT_USER: "SIGNOUT_USER",
  SIGNOUT_USER_SUCCESS: "SIGNOUT_USER_SUCCESS",
  SIGNOUT_USER_ERROR: "SIGNOUT_USER_ERROR",
  SET_USER: "SET_USER",
};
